#!/bin/bash

# COMANDOS DIRETOS - Execute no servidor alvo

echo "🔧 COMANDOS PARA EXECUTAR NO SERVIDOR ALVO"
echo "=========================================="
echo ""
echo "1. CORRIGIR SSH:"
echo "   sudo systemctl start ssh"
echo "   sudo systemctl enable ssh"
echo "   sudo systemctl status ssh"
echo ""
echo "2. CONFIGURAR SSH PORTA 22:"
echo "   sudo bash -c 'cat > /etc/ssh/sshd_config << EOF"
echo "Port 22"
echo "PermitRootLogin yes" 
echo "PasswordAuthentication yes"
echo "PermitEmptyPasswords no"
echo "X11Forwarding yes"
echo "UsePAM yes"
echo "EOF'"
echo ""
echo "3. REINICIAR SSH:"
echo "   sudo systemctl restart ssh"
echo ""
echo "4. DESABILITAR FIREWALL:"
echo "   sudo ufw --force disable"
echo ""
echo "5. USUÁRIO APOLO:"
echo "   sudo useradd -m -s /bin/bash apolo"
echo "   echo 'apolo:123456789' | sudo chpasswd"
echo "   sudo usermod -aG sudo apolo"
echo ""
echo "6. TESTAR:"
echo "   ssh apolo@localhost"
echo ""
echo "=========================================="